services:
  ghostposter:
    #build: .
    image: ghcr.io/limesdotpink/ghostposter:v2.0.0
    ports:
      - '3000:3000'
    hostname: ghostposter.local
    restart: unless-stopped
    volumes:
    - ./config.json:/usr/src/app/config.json

